# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker: 
      - image: circleci/node:12.18.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "builded" # run the `echo` command
  deploy:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - run: echo "deploied"
  start:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - run: echo "started"
orbs:
  slack: circleci/slack@3.4.2
workflows:
  project:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - start:
          requires:
            - build